### ISSUE TITLE
Add default export

### ISSUE THREAD

**Issue by pedroapfilho** [topojson/topojson-client#28]
Right now, the only way to add use the the `topojson-client` is to import it like this:

```
import * as topojson from "topojson-client";
```

What if we export it in a way that we can use it like:

```
import topojson from "topojson-client";
```

**Comment by mbostock** [comment]
No. If you want to import everything, use `*` to import the namespace. Otherwise, import specific symbols, *e.g.*, `import {feature} from "topojson-client";`. I don’t think it’s appropriate to make the namespace itself a symbol.
